src/Lambor/Controllers/DynamicPermissionsSampleController.cs
using System.ComponentModel;
using Lambor.Services.Identity;
using Lambor.ViewModels.Identity;
using DNTBreadCrumb.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lambor.Controllers
{
    /// <summary>
    /// More info: http://www.dotnettips.info/post/2581
    /// </summary>
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [BreadCrumb(UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("کنترلر نمونه با سطح دسترسی پویا")]
    public class DynamicPermissionsSampleController : Controller
    {
        [DisplayName("ایندکس")]
        [BreadCrumb(Order = 1)]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Index(RoleViewModel model)
        {
            return View(model);
        }

        [DisplayName("گزارش از لیست کتاب‌ها")]
        [BreadCrumb(Order = 1)]
        public IActionResult Books()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست مراجعان")]
        [BreadCrumb(Order = 1)]
        public IActionResult Users()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست امانات")]
        [BreadCrumb(Order = 1)]
        public IActionResult BooksGiven()
        {
            return View(viewName: "Index");
        }

        [DisplayName("گزارش از لیست مفقودی‌ها")]
        [BreadCrumb(Order = 1)]
        public IActionResult BooksMissings()
        {
            return View(viewName: "Index");
        }
    }
}

src/Lambor/Views/DynamicPermissionsSample/Index.cshtml
@model RoleViewModel
@{
    ViewData["Title"] = "مثالی دیگر از یک صفحه‌ی با سطح دسترسی پویا";
}

<div class="alert alert-warning mt-5">
    <a href="#" class="close" data-dismiss="alert">×</a>
    @ViewData["Title"] : @ViewContext.ActionDescriptor.DisplayName
</div>


<div class="card mt-5">
    <div class="card-header">
        <h5 class="card-title">@ViewData["Title"]</h5>
    </div>
    <div class="card-body">
        <form asp-controller="DynamicPermissionsSample"
              asp-action="Index"
              role="form"
              data-ajax="true"
              data-ajax-begin="dataAjaxBegin"
              data-ajax-success="dataAjaxSuccess"
              data-ajax-failure="dataAjaxFailure"
              method="post">
            <partial name="_CustomValidationSummary" />
            <div class="form-group row">
                <label asp-for="Name" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    <input dir="ltr" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-md-2 col-md-10">
                    <button type="submit" class="btn btn-info">ارسال جهت مشاهده mvcContext.HttpContext.Request.Form</button>
                </div>
            </div>
        </form>
    </div>
</div>