src/Lambor/Areas/Identity/Controllers/UsersManagerController.cs
using Lambor.Common.IdentityToolkit;
using Lambor.Entities.Identity;
using Lambor.Services.Contracts.Identity;
using Lambor.Services.Identity;
using Lambor.ViewModels.Identity;
using DNTBreadCrumb.Core;
using DNTCommon.Web.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Lambor.Areas.Identity.Controllers
{
    [Authorize(Roles = ConstantRoles.Admin)]
    [Area(AreaConstants.IdentityArea)]
    [BreadCrumb(Title = "مدیریت کاربران", UseDefaultRouteUrl = true, Order = 0)]
    public class UsersManagerController : Controller
    {
        private const int DefaultPageSize = 7;

        private readonly IApplicationRoleManager _roleManager;
        private readonly IApplicationUserManager _userManager;

        public UsersManagerController(
            IApplicationUserManager userManager,
            IApplicationRoleManager roleManager)
        {
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _roleManager = roleManager ?? throw new ArgumentNullException(nameof(roleManager));
        }

        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> ActivateUserEmailStat(int userId)
        {
            User thisUser = null;
            var result = await _userManager.UpdateUserAndSecurityStampAsync(
                userId, user =>
                {
                    user.EmailConfirmed = true;
                    thisUser = user;
                });
            if (!result.Succeeded)
            {
                return BadRequest(error: result.DumpErrors(useHtmlNewLine: true));
            }

            return await returnUserCardPartialView(thisUser);
        }

        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> ChangeUserLockoutMode(int userId, bool activate)
        {
            User thisUser = null;
            var result = await _userManager.UpdateUserAndSecurityStampAsync(
                userId, user =>
                {
                    user.LockoutEnabled = activate;
                    thisUser = user;
                });
            if (!result.Succeeded)
            {
                return BadRequest(error: result.DumpErrors(useHtmlNewLine: true));
            }

            return await returnUserCardPartialView(thisUser);
        }

        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> ChangeUserRoles(int userId, int[] roleIds)
        {
            User thisUser = null;
            var result = await _userManager.AddOrUpdateUserRolesAsync(
                userId, roleIds, user => thisUser = user);
            if (!result.Succeeded)
            {
                return BadRequest(error: result.DumpErrors(useHtmlNewLine: true));
            }

            return await returnUserCardPartialView(thisUser);
        }

        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> ChangeUserStat(int userId, bool activate)
        {
            User thisUser = null;
            var result = await _userManager.UpdateUserAndSecurityStampAsync(
                userId, user =>
                        {
                            user.IsActive = activate;
                            thisUser = user;
                        });
            if (!result.Succeeded)
            {
                return BadRequest(error: result.DumpErrors(useHtmlNewLine: true));
            }

            return await returnUserCardPartialView(thisUser);
        }

        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> CreateUserApi(int userId)
        {
            User thisUser = null;
            thisUser = await _userManager.CreateUserApiKey(userId);
            return await returnUserCardPartialView(thisUser);
        }

        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> ChangeUserTwoFactorAuthenticationStat(int userId, bool activate)
        {
            User thisUser = null;
            var result = await _userManager.UpdateUserAndSecurityStampAsync(
                userId, user =>
                {
                    user.TwoFactorEnabled = activate;
                    thisUser = user;
                });
            if (!result.Succeeded)
            {
                return BadRequest(error: result.DumpErrors(useHtmlNewLine: true));
            }

            return await returnUserCardPartialView(thisUser);
        }

        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> EndUserLockout(int userId)
        {
            User thisUser = null;
            var result = await _userManager.UpdateUserAndSecurityStampAsync(
                userId, user =>
                {
                    user.LockoutEnd = null;
                    thisUser = user;
                });
            if (!result.Succeeded)
            {
                return BadRequest(error: result.DumpErrors(useHtmlNewLine: true));
            }

            return await returnUserCardPartialView(thisUser);
        }

        [BreadCrumb(Title = "ایندکس", Order = 1)]
        public async Task<IActionResult> Index(int? page = 1, string field = "Id", SortOrder order = SortOrder.Ascending)
        {
            var model = await _userManager.GetPagedUsersListAsync(
                pageNumber: page.Value - 1,
                recordsPerPage: DefaultPageSize,
                sortByField: field,
                sortOrder: order,
                showAllUsers: true);

            model.Paging.CurrentPage = page.Value;
            model.Paging.ItemsPerPage = DefaultPageSize;
            model.Paging.ShowFirstLast = true;

            if (HttpContext.Request.IsAjaxRequest())
            {
                return PartialView("_UsersList", model);
            }
            return View(model);
        }

        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> SearchUsers(SearchUsersViewModel model)
        {
            var pagedUsersList = await _userManager.GetPagedUsersListAsync(
                model: model,
                pageNumber: 0);

            pagedUsersList.Paging.CurrentPage = 1;
            pagedUsersList.Paging.ItemsPerPage = model.MaxNumberOfRows;
            pagedUsersList.Paging.ShowFirstLast = true;

            model.PagedUsersList = pagedUsersList;
            return PartialView("_SearchUsers", model);
        }

        private async Task<IActionResult> returnUserCardPartialView(User thisUser)
        {
            var roles = await _roleManager.GetAllCustomRolesAsync();
            return PartialView("~/Areas/Identity/Views/UserCard/_UserCardItem.cshtml",
                new UserCardItemViewModel
                {
                    User = thisUser,
                    ShowAdminParts = true,
                    Roles = roles,
                    ActiveTab = UserCardItemActiveTab.UserAdmin
                });
        }
    }
}

src/Lambor/Controllers/ProductController.cs
using DNTBreadCrumb.Core;
using DNTCommon.Web.Core;
using Lambor.Services.Contracts;
using Lambor.Services.Identity;
using Lambor.ViewModels.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace Lambor.Controllers
{


    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [BreadCrumb(UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("مدیریت محصولات")]
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IBrandService _brandService;
        private const string ProductNotFound = "محصول مورد نظر یافت نشد";
        private const string UploadDirectoryName = "Uploads";

        public ProductController(IProductService productService, ICategoryService categoryService, IBrandService brandService, IWebHostEnvironment webHostEnvironment)
        {
            _productService = productService ?? throw new ArgumentNullException(nameof(productService));
            _categoryService = categoryService;
            _brandService = brandService;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index(int? page = 1)
        {
            var products = await _productService.GetPagedProductListAsync(page.Value - 1, 7);
            return View(products);
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(ModifyProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.ProductImage != null && model.ProductImage.Length > 0)
                {
                    var saveResult = await SaveAndReturnAddress(model.ProductImage);
                    if (!string.IsNullOrWhiteSpace(saveResult.Error))
                    {
                        return BadRequest(saveResult.Error);
                    }
                    model.Image = saveResult.Address;
                }
                await _productService.InsertAsync(model);
            }
            return Ok();
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ModifyProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = await _productService.GetAsync(model.Id);
                if (product == null)
                {
                    ModelState.AddModelError("", ProductNotFound);
                }
                else
                {

                    product.Name = model.Name;
                    product.Price = model.Price;
                    product.Description = model.Description;
                    product.CategoryId = model.CategoryId;
                    product.BrandId = model.BrandId;

                    product.Image = model.Image;

                    if (model.ProductImage.Length > 0)
                    {
                        var saveResult = await SaveAndReturnAddress(model.ProductImage);
                        if (!string.IsNullOrWhiteSpace(saveResult.Error))
                        {
                            return BadRequest(saveResult.Error);
                        }
                        model.Image = saveResult.Address;
                    }
                    await _productService.UpdateAsync(model);
                }
            }

            return Ok();
        }

        public async Task<IActionResult> Delete(ProductViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (string.IsNullOrWhiteSpace(model?.Id.ToString()))
            {
                return BadRequest("model is null.");
            }

            var product = await _productService.GetAsync(model.Id);
            if (product == null)
            {
                ModelState.AddModelError("", ProductNotFound);
            }
            else
            {
                await _productService.DeleteAsync(product.Id);
            }
            return Ok();
        }

        [AjaxOnly]
        public async Task<IActionResult> Render([FromBody] ModelIdViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var viewModel = new ProductRenderViewModel();
            viewModel.Product = new ProductViewModel();

            if (model == null || model.Id == 0)
            {
                await FillProductComboCollections(viewModel);
                return PartialView("_Create", model: viewModel);
            }

            var product = await _productService.GetAsync(model.Id);
            if (product == null)
            {
                ModelState.AddModelError("", ProductNotFound);
                await FillProductComboCollections(viewModel);
                return PartialView("_Create", model: viewModel);
            }

            viewModel.Product = new ProductViewModel { Id = product.Id, Name = product.Name, Price = product.Price, Description = product.Description, CategoryId = product.CategoryId, Image = product.Image };
            await FillProductComboCollections(viewModel, product.CategoryId, product.BrandId);
            return PartialView("_Create", model: viewModel);
        }

        private async Task FillProductComboCollections(ProductRenderViewModel productViewModel, int? categoryId = null, int? brandId = null)
        {
            productViewModel.Categories = new SelectList(await _categoryService.GetAllForDropdown(), "Id", "Name", categoryId);
            productViewModel.Brands = new SelectList(await _brandService.GetAllForDropdown(), "Id", "Name", brandId);

        }

        [AjaxOnly]
        public async Task<IActionResult> RenderDelete([FromBody] ModelIdViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (model == null)
            {
                return BadRequest("model is null.");
            }

            var product = await _productService.GetAsync(model.Id);
            if (product == null)
            {
                ModelState.AddModelError("", ProductNotFound);
                return PartialView("_Delete", model: new ProductViewModel());
            }
            return PartialView("_Delete", model: new ProductViewModel { Id = product.Id, Name = product.Name, Price = product.Price, Description = product.Description, CategoryId = product.CategoryId, Image = product.Image });
        }



        private string GetUploadDirectoryPath()
        {
            var uploadDirectoryPath = Path.Combine(_webHostEnvironment.WebRootPath, UploadDirectoryName);
            if (!Directory.Exists(uploadDirectoryPath))
            {
                Directory.CreateDirectory(uploadDirectoryPath);
            }

            return uploadDirectoryPath;
        }

        private async Task<(string Address, string Error)> SaveAndReturnAddress(IFormFile file)
        {

            if (file.Length == 0) return (null, "فایل یافت نشد");
            if (file.Length > 5 * 1024 * 1024) return (null, "حجم مجاز عکس 5 مگابایت است");

            var uploadDirectoryPath = GetUploadDirectoryPath();
            var fileName = $"{Guid.NewGuid()}_" + file.FileName;
            var filePath = Path.Combine(uploadDirectoryPath, fileName);

            await using Stream fileStream = new FileStream(filePath, FileMode.Create);

            await file.CopyToAsync(fileStream);

            return ($"{UploadDirectoryName}/{fileName}", null);
        }
    }

}

src/Lambor/Views/Product/Index.cshtml
@model PagedProductViewModel

@{
    ViewData["Title"] = "مدیریت محصولات";
}


<div class="card mt-5">
    <div class="card-header">
        <h5 class="card-title">@ViewData["Title"]</h5>
    </div>
    <div class="card-body">
        <partial name="_AllProductList" model="Model.Items" />
    </div>
    <footer class="card-footer">
        <a class="btn btn-success" href="#" id="btnCreate">ایجاد محصول جدید</a>
    </footer>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $('#btnCreate').click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند

                $.bootstrapModalAjaxForm({
                    postUrl: '@Url.Action("Add", "Product")',
                    renderModalPartialViewUrl: '@Url.Action("Render", "Product")',
                    renderModalPartialViewData: JSON.stringify({ "id": 0 }),
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                        location.reload();
                    },
                    fileInputIds:['ProductImage']
                });
            });

            $("a[id^='btnEdit']").click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند
                var productId = $(this).data("edit-id");
                $.bootstrapModalAjaxForm({
                    postUrl: '@Url.Action("Edit", "Product")',
                    renderModalPartialViewUrl: '@Url.Action("Render", "Product")',
                    renderModalPartialViewData: JSON.stringify({ "id": productId }),
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                        location.reload();
                    },
                    fileInputIds:['ProductImage']
                });
            });

            $("a[id^='btnDelete']").click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند
                var productId = $(this).data("delete-id");

                $.bootstrapModalAjaxForm({
                    postUrl: '@Url.Action("Delete", "Product")',
                    renderModalPartialViewUrl: '@Url.Action("RenderDelete", "Product")',
                    renderModalPartialViewData: JSON.stringify({ "id": productId }),
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                        location.reload();
                    }
                });
            });
        });
    </script>
}

<div>
    <cs-pager cs-paging-pagesize="@Model.Paging.ItemsPerPage"
              cs-paging-pagenumber="@Model.Paging.CurrentPage"
              cs-paging-totalitems="@Model.Paging.TotalItems"
              cs-pagenumber-param="page"
              cs-ajax-target="#gridcontainer"
              asp-controller="UsersManager"
              asp-action="Index"
              asp-route-pagesize="@Model.Paging.ItemsPerPage"
              cs-show-first-last="true"
              cs-suppress-empty-nextprev="true"
              cs-suppress-inactive-firstlast="true"
              cs-first-page-text="ابتدا"
              cs-last-page-text="انتها"
              cs-pager-li-current-class="active"
              cs-pager-li-non-active-class="disabled"
              cs-pager-ul-class="pagination"
              cs-pager-li-current-class="page-item active"
              cs-pager-li-other-class="page-item"
              cs-pager-li-non-active-class="page-item disabled"
              cs-pager-link-current-class="page-link"
              cs-pager-link-other-class="page-link"></cs-pager>
</div>

src/Lambor/Views/Product/_AllProductList.cshtml
@model List<ProductViewModel>

<div class="table-responsive">
  <table id="all-product-list" class="table table-striped table-hover table-bordered">
   <thead class="thead-light">
    <tr>
        <th class="text-center">عکس </th>
        <th class="text-center">نام </th>
        <th class="text-center">برند</th>
        <th class="text-center">قیمت</th>
        <th class="text-center">دسته بندی</th>
        <th class="text-center">شرح</th>
        <th class="text-center">عملیات</th>
       
    </tr>
   </thead>
   <tbody>
    @if (!Model.Any())
            {
        <tr>
            <td colspan="7" class="text-center">محصول یافت نشد</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            
            <tr>
                <td class="text-center"><img src="@(string.IsNullOrWhiteSpace(item.Image)?"/images/product.png":item.Image)" class="rounded img-thumbnail" height="50" width="50" /></td>
                <td class="text-center">@item.Name</td>
                <td class="text-center">@item.BrandName</td>
                <td class="text-center">@item.Price</td>
                <td class="text-center">@item.CategoryName</td>
                <td class="text-center">@item.Description</td>

                
                <td class="text-center">
                    <a href="#" id="btnEdit-@item.Id" data-edit-id="@item.Id" class="btn btn-sm btn-primary">ویرایش</a>
                    <a href="#" id="btnDelete-@item.Id" data-delete-id="@item.Id" class="btn btn-sm btn-danger">حذف</a>
                </td>
               
               
            </tr>
        }
    }
  </tbody>
 </table>
</div>

src/Lambor/Views/Product/_Create.cshtml
@model ProductRenderViewModel

<partial name="_CustomValidationSummary" />
<form asp-action="Add" method="post" enctype="multipart/form-data">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                @if (Model.Product.Id == 0)
                {
                    <h4 class="modal-title">ایجاد محصولات جدید</h4>
                }
                else
                {
                    <h4 class="modal-title">ویرایش محصول</h4>
                }
            </div>
            <div class="modal-body">
                <input asp-for="Product.Id" name="Id" />

                <div class="form-group row">
                    <label asp-for="Product.Name" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">
                        <input dir="ltr" asp-for="Product.Name" class="form-control" name="Name" />
                        <span asp-validation-for="Product.Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Product.Price" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">
                        <input dir="ltr" asp-for="Product.Price" class="form-control" name="Price" />
                        <span asp-validation-for="Product.Price" class="text-danger"></span>
                    </div>
                </div>




                <div class="form-group row">
                    <label asp-for="Product.Description" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">
                        <input dir="ltr" asp-for="Product.Description" class="form-control" name="Description" />
                        <span asp-validation-for="Product.Description" class="text-danger"></span>
                    </div>
                </div>
                @{
                    /*Category ComboBox}*/
                }
                <div class="form-group row">
                    <label asp-for="Product.CategoryId" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">

                        <select dir="ltr" asp-for="Product.CategoryId" asp-items="Model.Categories" class="form-control" name="CategoryId">
                        </select>
                        <span asp-validation-for="Product.CategoryId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Product.BrandId" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">

                        <select dir="ltr" asp-for="Product.BrandId" asp-items="Model.Brands" class="form-control" name="BrandId">
                        </select>
                        <span asp-validation-for="Product.BrandId" class="text-danger"></span>
                    </div>
                </div>


                <div class="form-group row">
                    <label asp-for="Product.BrandId" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">
                        <input type="hidden" asp-for="Product.Image" />
                        @if (!string.IsNullOrWhiteSpace(Model.Product.Image))
                        {
                            <img src="@Model.Product.Image" class="img-thumbnail" />
                        }
                        <input name="ProductImage" id="ProductImage" type="file" accept=".jpg,jpeg,png" />
                        <span asp-validation-for="Product.Image" class="text-danger"></span>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="submit">ثبت</button>
                <button class="btn" data-dismiss="modal" aria-hidden="true">انصراف</button>
            </div>
        </div>
    </div>
</form>

src/Lambor/Views/Product/_Delete.cshtml
@model ProductViewModel
<partial name="_CustomValidationSummary" />
<form asp-action="Delete" method="post" class="form-horizontal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">حذف محصول</h4>
            </div>
            <div class="modal-body">
                <span class="text-center">
                    آیا می‌خواهید 
                    <strong>@Model.Name</strong>
                    را حذف کنید؟
                    <br/>
                    
                </span>
                <input asp-for="Id" />
                <input type="hidden" asp-for="Name">
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="submit">تائید حذف</button>
                <button class="btn" data-dismiss="modal" aria-hidden="true">انصراف</button>
            </div>
        </div>
    </div>
</form>